---
name: 'Create Zip'

on:
  workflow_dispatch:

permissions: write-all
jobs:
  create-zip:
    name: 'Create Zip'
    runs-on: 'ubuntu-latest'
    outputs:
      version: ${{ steps.read_version.outputs.version }}
      zip_name: ${{ steps.zip_project.outputs.zip_name }}

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: 🤔 Read version and project name from package.json
        id: read_version
        run: |

          VERSION=$(jq -r '.version' < package.json)
          PROJECT_NAME=$(jq -r '.name' < package.json)
          echo "Version is $VERSION"
          echo "Project name is $PROJECT_NAME"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: 🤞 Install dependencies
        run: |
          [ -f "package.json" ] && npm install --no-fund --silent || echo "No package.json file found"
          [ -f "composer.json" ] && composer install --no-dev --quiet || echo "No composer.json file found"

      - name: 📚 Convert Readme.md to WordPress Readme
        uses: everpress-co/action-md2wp@main

      - name: 🏗️ Build
        run: |
          npm run build --no-dev

      - name: 🗜️ Zip the contents of the dist directory with project name and version
        id: zip_project
        if: ${{ !env.ACT }}
        run: |
          ZIP_NAME="${{ steps.read_version.outputs.project_name }}.zip"
          npm run plugin-zip
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add $ZIP_NAME -f
          git commit -m "added file $ZIP_NAME"
          git push
